const Transaction = require('../models/Transaction');
const Product = require('../models/Product');
const Expense = require('../models/Expense');
const Customer = require('../models/Customer');

exports.sync = async (req, res) => {
    try {
        const { transactions, products, expenses, customers } = req.body;

        // 1. Process Transactions (Insert new ones)
        if (transactions && transactions.length > 0) {
            // Using bulkWrite for upserting based on transactionId to prevent duplicates
            const transactionOps = transactions.map(trx => ({
                updateOne: {
                    filter: { transactionId: trx.transactionId },
                    update: { $set: trx },
                    upsert: true
                }
            }));
            await Transaction.bulkWrite(transactionOps);
        }

        // 2. Process Expenses (Insert new ones)
        if (expenses && expenses.length > 0) {
            const expenseOps = expenses.map(exp => ({
                insertOne: {
                    document: exp
                }
            }));
            // Note: Expenses might not have unique IDs generated by client, so simple insert might be better
            // OR client should generate UUIDs. Assuming client sends new expenses.
            await Expense.insertMany(expenses);
        }

        // 3. Process Products (Update stock/price from client if needed, OR just return server source of truth)
        // For now, let's assume Back Office is the source of truth for Product Definitions,
        // but Desktop might send stock decrements.
        // A simple strategy: Return all products from server to client.
        const allProducts = await Product.find({});

        // 4. Process Customers (Update balances)
        if (customers && customers.length > 0) {
             const customerOps = customers.map(cust => ({
                updateOne: {
                    filter: { phone: cust.phone }, // Assuming phone is unique identifier
                    update: { $set: cust },
                    upsert: true
                }
            }));
            await Customer.bulkWrite(customerOps);
        }
        const allCustomers = await Customer.find({});

        res.json({
            success: true,
            message: 'Sync successful',
            data: {
                products: allProducts,
                customers: allCustomers
            }
        });

    } catch (error) {
        console.error('Sync Error:', error);
        res.status(500).json({ success: false, message: 'Sync failed', error: error.message });
    }
};

exports.getProducts = async (req, res) => {
    try {
        const products = await Product.find({});
        res.json({ products });
    } catch (error) {
        res.status(500).json({ error: 'Failed to fetch products' });
    }
};

exports.createTransaction = async (req, res) => {
    try {
        const transaction = new Transaction(req.body);
        await transaction.save();
        res.json({ success: true, transactionId: transaction.transactionId });
    } catch (error) {
        res.status(500).json({ error: 'Failed to create transaction' });
    }
};
